DoAnCs/Areas/Admin/Controllers/DeThiController.cs
using System.IO;

using System.Linq.Dynamic;
using DoAnCs.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json; // Cần thư viện Newtonsoft.Json
using System.Net;
using PagedList;
using DoAnCs.Models.Viewmodel;
using System.Data.Entity.Infrastructure;
using System.Windows.Interop;
using Org.BouncyCastle.Asn1.Crmf;
using DoAnCs.Areas.Admin.Controllers.customAuthen;
using System.Web.Security;

namespace DoAnCs.Areas.Admin.Controllers
{
    [CustomAuthorize(Roles = "Admin")]

    public class DeThiController : Controller
    {
        TracNghiemEntities1 db = new TracNghiemEntities1();
        // GET: Admin/BaiThi
        public ActionResult Index()
        {
            var item = db.Exams.OrderByDescending(x=>x.IdSubject).ToList();
            return View(item);
        }

        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.IdSubject = new SelectList(db.Subjects, "IdSubject", "NameSubject");
            return View();


        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Exam exam)
        {
            if (ModelState.IsValid)
            {
                exam.Exam_date = DateTime.Now;
                db.Exams.Add(exam);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdSubject = new SelectList(db.Subjects, "IdSubject", "NameSubject");

            return View(exam);
        }
        public ActionResult edit(int id)
        {
            ViewBag.IdSubject = new SelectList(db.Subjects, "IdSubject", "NameSubject");

            var exem = db.Exams.Find(id);
            return View(exem);
        }
        [HttpPost]
        public ActionResult edit(Exam exem)
        {
            if (ModelState.IsValid)
            {
                db.Exams.Attach(exem);
                db.Entry(exem).State = System.Data.Entity.EntityState.Modified;
                //var lectured = (Lecturer)Session["TaiKhoanGV"];
                exem.ModifierDate = DateTime.Now;
                if (User.Identity.IsAuthenticated)
                {
                    var userName = User.Identity.Name;
                    exem.MordifierBy = userName;
                }

                db.SaveChanges();
                return Json(new { success = true });
            }
            ViewBag.IdSubject = new SelectList(db.Subjects, "IdSubject", "NameSubject");

            return Json(new { msg = "Không thể xóa câu hỏi khỏi đợt thi." });
        }
        //Xóa Không load trang khác  
        [HttpPost]
        public ActionResult Delete1(int id)
        {
            try
            {
                if (id != 0)
                {
                    var examToDelete = db.Exams.Find(id);

                    if (examToDelete != null) // Kiểm tra xem bản ghi có tồn tại không
                    {
                        db.Exams.Remove(examToDelete);
                        db.SaveChanges();
                        TempData["Succes"] = "Xóa Thành Công";
                        return Json(new { success = true });
                    }
                    else
                    {
                        TempData["warning"] = "Lỗi Không Tìm Thấy Bbản Ghi";
                        return Json(new { success = false, message = "Không tìm thấy bản ghi để xóa." });
                    }
                }
                else
                {
                    TempData["warning"] = "Lỗi Không Tìm Thấy Bbản Ghi";
                    return Json(new { success = false, message = "ID không hợp lệ." });
                }
            }
            catch (Exception e)
            {

                TempData["warning"] = "Có lỗi xảy ra khi xóa bản ghi.";
                Console.WriteLine($"Processing failed: {e.Message}");
                return Json(new { success = false, message = "Có lỗi xảy ra khi xóa bản ghi." });

            }
        }



        public ActionResult GetList()
        {
            int start = Convert.ToInt32(Request["start"]);
            int length = Convert.ToInt32(Request["length"]);
            string searchValue = Request["search[value]"];
            string sortColumnName = Request["columns[" + Request["order[0][column]"] + "][name]"];
            string sortDirection = Request["order[0][dir]"];

            List<Question> empList = new List<Question>();

            empList = db.Questions.ToList<Question>();
            int totalrows = empList.Count;
            if (!string.IsNullOrEmpty(searchValue)) //filter
            {
                empList = empList
                    .Where(x => x.Contentt.ToLower().Contains(searchValue.ToLower()) || x.Topic.NameTopic.ToLower().Contains(searchValue.ToLower()))
                    .ToList<Question>();
            }
            int totalrowsafterfiltering = empList.Count;

            // Selecting only specific columns (ID, Content, and Topic)
            var selectedData = empList
                .Select(q => new
                {
                    q.IdQuestion,
                    q.Contentt,
                    TopicName = q.Topic.NameTopic
                })
                .ToList();

            // Sorting
            if (!string.IsNullOrEmpty(sortColumnName))
            {
                if (sortDirection == "asc")
                {
                    selectedData = selectedData.OrderBy(sortColumnName).ToList();
                }
                else
                {
                    selectedData = selectedData.OrderBy(sortColumnName).ToList();
                }
            }

            // Paging
            selectedData = selectedData.Skip(start).Take(length).ToList();

            return Json(new
            {
                data = selectedData,
                draw = Request["draw"],
                recordsTotal = totalrows,
                recordsFiltered = totalrowsafterfiltering
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Partial_CauHoi123()
        {
            var empList = db.Questions.ToList<Question>();
            return PartialView("Partial_CauHoi123", empList);
        }


        [HttpGet]

        public ActionResult Partial_CauHoi(int? idExam, int? page)
        {
            var item = db.Questions.ToList();

            int pageIndex = (page ?? 1);
            int pagesize = 5;

            var pagedItems = item.ToPagedList(pageIndex, pagesize);

            ViewBag.PageSize = pagesize;
            ViewBag.Page = page;
            ViewBag.TotalPages = pagedItems.PageCount;

            return PartialView(pagedItems);
        }
        [HttpGet]
        public ActionResult Chitiet(int? id)
        {

            ViewBag.IdSubject = new SelectList(db.Subjects, "IdSubject", "NameSubject");

            var exem = db.Exams.Find(id);
            return View(exem);
        }
        [HttpGet]
        public ActionResult CauHoiInBaiThi(int? id)
        {
            List<object> selectedQuestions = new List<object>();

            Exam exam = db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            else
            {
                var questionIds = db.Question_Exam
                    .Where(mapping => mapping.IdExam == exam.IdExam)
                    .Select(mapping => mapping.IdQuestion)
                    .ToList();

                var questions = db.Questions
                    .Where(q => questionIds.Contains(q.IdQuestion))
                    .Select(q => new
                    {
                        IdQuestion = q.IdQuestion,
                        Contentt = q.Contentt,
                        TopicName = q.Topic.NameTopic
                    })
                    .ToList();

                return Json(questions, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult CauHoiChuaCoTrongBaiThi(int? id)
        {
            List<object> unselectedQuestionList = new List<object>();

            Exam exam = db.Exams.Find(id);
            if (exam == null)
            {
                return HttpNotFound();
            }
            else
            {
                var questionIds = db.Question_Exam
                    .Where(mapping => mapping.IdExam == exam.IdExam)
                    .Select(mapping => mapping.IdQuestion)
                    .ToList();

                var unselectedQuestionIds = db.Questions
                    .Where(q => !questionIds.Contains(q.IdQuestion))
                    .Select(q => q.IdQuestion)
                    .ToList();

                var unselectedQuestions = db.Questions
                    .Where(q => unselectedQuestionIds.Contains(q.IdQuestion))
                    .Select(q => new
                    {
                        IdQuestion = q.IdQuestion,
                        Contentt = q.Contentt,
                        TopicName = q.Topic.NameTopic
                    })
                    .ToList();

                return Json(unselectedQuestions, JsonRequestBehavior.AllowGet);
            }
        }


        public ActionResult CauHoiKhongthuocBaiThi()
        {
            return PartialView();
        }
        public ActionResult XoaCauHoi1(int? examId, int? questionId)
        {
            if (examId == null || questionId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Exam exam = db.Exams.Find(examId);
            if (exam == null)
            {
                return HttpNotFound();
            }

            var mappingToRemove = db.Question_Exam.FirstOrDefault(mapping => mapping.IdExam == examId && mapping.IdQuestion == questionId);

            if (mappingToRemove != null)
            {
                db.Question_Exam.Remove(mappingToRemove);


                exam.NumberQ -= 1;


                if (exam.NumberQ >= 0)

DoAnCs/Areas/Admin/Views/DeThi/Add.cshtml
@model DoAnCs.Models.Exam

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_layout.cshtml";
}

@section naviheader{
    <h1>Quản Lý Đề Thi</h1>
    <ul class="breadcrumb">
        <li>
            <a href="#">Home</a>
        </li>
        <li><i class='bx bx-chevron-right'></i></li>
        <li>
            <a class="active" href="#">Quản Lý Đề Thi</a>
        </li>
        <li><i class='bx bx-chevron-right'></i></li>
        <li>
            <a class="active" href="#">Thêm Đề Thi</a>
        </li>
    </ul>


}
<div class="order">
    <div class="head">

        <i class="bx bx-search"></i>
        <i class="bx bx-filter"></i>
    </div>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông Tin thêm mới</h3>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    @using (Html.BeginForm("AddExamWithQuestions", "DeThi", FormMethod.Post, new { id = "examForm" }))

                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        <!-- your steps content here -->
                    <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Tên Đề Thi</label>
                            @Html.TextBoxFor(x => x.NameExam, new { @class = "form-control", @placeholder = "Tên Môn Học", @required = "required" })
                            @Html.ValidationMessageFor(x => x.NameExam, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label class="">Tên Môn Học</label>

                            @Html.DropDownList("IdSubject", null, htmlAttributes: new { @class = "form-control", @required = "required" })
                            @Html.ValidationMessageFor(model => model.IdSubject, "", new { @class = "text-danger" })

                        </div>
                        <div class="form-group">
                            <label for="Time">Thời Gian</label>
                            @Html.TextBoxFor(x => x.Time, new { @class = "form-control", @required = "required" })
                            @Html.ValidationMessageFor(x => x.Time, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Số Câu Hỏi</label>
                            @Html.TextBoxFor(x => x.NumberQ, new { @class = "form-control", @required = "required" })
                            @Html.ValidationMessageFor(x => x.NumberQ, null, new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Ảnh</label>
                            <textarea class="form-control" name="image" id="inputContentt"></textarea>
                        </div>
                        <br />

                        <h4>Chọn Câu Hỏi </h4>
                        <h6 class="socauchon">Số Câu Đã Chọn : <span id="socauchon">0</span></h6>

                        <table class="table">

                            @Html.Action("Partial_CauHoi123", "DeThi")

                        </table>


                        <div class="form-group">
                            <a href="/admin/productcategory" class="btn btn-danger">Quay Lại</a>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                    }
                    <button type="button" id="submitButton" class="btn btn-primary">Chọn Câu Hỏi</button>

                </div>
            </div>


        </div>
        <!-- /.card-body -->
        <!-- /.card-footer-->
    </div>

</div>
@section scripts{
    <script>

        document.addEventListener("DOMContentLoaded", function () {



            CKEDITOR.replace('inputContentt', {
                removeButtons: 'Link,Unlink,Anchor,Form,Checkbox,Textarea,Button,ImageButton,HiddenField,TextField,SelectAll,Replace,Find,Redo,Undo,Paste,Copy,Cut,Templates,Print,Preview,Save,NewPage,Smiley,Flash,Maximize,ShowBlocks,Scayt,Indent,Outdent,Blockquote,CreateDiv,BidiLtr,BidiRtl,Language,PageBreak,Iframe,SpecialChar,Smiley,HorizontalRule,Radio,Select,PasteText,PasteFromWord,Source,Bold,Italic,Underline,Strike,Superscript,Subscript,CopyFormatting,RemoveFormat,NumberedList,BulletedList,JustifyLeft,JustifyCenter,JustifyRight,JustifyBlock,Table,Styles,Format,Font,FontSize,TextColor,BGColor,About'

            });




            function BrowseServer() {
                var finder = new CKFinder();
                finder.selectActionFunction = URlHinhAnh;
                finder.popup();
            }
            function URlHinhAnh(url) {
                $("input[name=HinhAnh]").val(url);
            }
            // Lấy thẻ checkbox "selectAllCheckbox"
            var selectAllCheckbox = document.getElementById("selectAllCheckbox");

            // Lấy tất cả các checkbox với class "cbkItem"
            var checkboxes = document.querySelectorAll(".cbkItem");

            // Xử lý sự kiện khi người dùng nhấp vào "selectAllCheckbox"
            selectAllCheckbox.addEventListener("change", function () {
                checkboxes.forEach(function (checkbox) {
                    checkbox.checked = selectAllCheckbox.checked;
                });
            });

            // Lấy giá trị của các ô được chọn khi nhấp vào nút button
            var button = document.getElementById("submitButton");
            button.addEventListener("click", function () {
                var selectedValues = [];
            checkboxes.forEach(function (checkbox) {
                    if (checkbox.checked) {
                selectedValues.push(checkbox.value);
                    }
                });
            // In ra giá trị các ô được chọn

                console.log(selectedValues);
                 $.ajax({
                url: "@Url.Action("AddExamWithQuestions", "DeThi")", // Điều chỉnh đường dẫn và tên controller nếu cần
                type: "POST",
                data: $("#examForm").serialize(), // Gửi dữ liệu form
                success: function (data) {
                    // Xử lý kết quả ở đây nếu cần
                    alert("Success!");
                },
                error: function (xhr, status, error) {
                    // Xử lý lỗi ở đây nếu cần
                    alert("Error: " + error);
                }
            });
            });
        });


    </script>









}

DoAnCs/Areas/Admin/Views/DeThi/Addtest.cshtml
@model DoAnCs.Models.Exam

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_layout.cshtml";
}

@section naviheader{
    <h1>Quản Lý Đề Thi</h1>
    <ul class="breadcrumb">
        <li>
            <a href="#">Home</a>
        </li>
        <li><i class='bx bx-chevron-right'></i></li>
        <li>
            <a class="active" href="#">Quản Lý Đề Thi</a>
        </li>
        <li><i class='bx bx-chevron-right'></i></li>
        <li>
            <a class="active" href="#">Thêm Đề Thi</a>
        </li>
    </ul>


}
<div class="order">
    <div class="head">


    </div>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông Tin thêm mới</h3>
            <button type="button" id="submitcl123" style="float:right;" class="btn btn-success">Thêm Đề Thi</button>

        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    @using (Html.BeginForm("AddExamWithQuestions", "DeThi", FormMethod.Post, new { id = "examForm", enctype = "multipart/form-data" }))
                    {
                        @*<form id="examForm" method="post" enctype="multipart/form-data">*@
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        <!-- your steps content here -->
                        <div id="logins-part" class="content active dstepper-block" role="tabpanel" aria-labelledby="logins-part-trigger">
                            <div class="form-group">
                                <label class="text-primary" for="exampleInputEmail1">Tên Đề Thi</label>
                                @Html.TextBoxFor(x => x.NameExam, new { @class = "form-control", @placeholder = "Tên Môn Học", @required = "required" })
                                @Html.ValidationMessageFor(x => x.NameExam, null, new { @class = "text-danger" })
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label class="text-primary">Tên Môn Học</label>

                                        @Html.DropDownList("IdSubject", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.IdSubject, "", new { @class = "text-danger" })

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    @*<textarea class="form-control" name="image1" id="inputContentt2"></textarea>
                                        @Html.TextAreaFor(x => x.image, new { @class = "form-control", @id= "inputContentt" })*@

                                </div>

                            </div>

                            <div class="row">


                                <div class="col-md-4">
                                    <label class="text-primary" for="Time">Thời Gian</label>
                                    @Html.TextBoxFor(x => x.Time, new { @class = "form-control", @type = "number", @min = 0, @max = 100, @required = "required" })
                                    @Html.ValidationMessageFor(x => x.Time, null, new { @class = "text-danger" })
                                </div>
                                <div class="col-md-4">
                                    <label class="text-primary" for="">Số Câu Hỏi</label>
                                    @Html.TextBoxFor(x => x.NumberQ, new { @class = "form-control", @Value = 0, @id = "socauhoi1"  })
                                    @Html.ValidationMessageFor(x => x.NumberQ, null, new { @class = "text-danger" })
                                </div>
                                <div class="col-md-4">
                                    <label class="text-primary" for="d">Ngày Tạo</label>
                                    <input type="text" class="form-control" name="d" value="@ViewBag.datetimnow" readonly />
                                </div>

                            </div>
                            <div class="form-check">
                                <label class="text-primary">Hiển Thị</label>

                                @Html.EditorFor(x => x.isactive, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.isactive, null, new { @class = "text-danger" })

                            </div>




                            <section id="divthemcauhoi">
                                <h4 class="text-info">Chọn Câu Hỏi </h4>
                                <h6 class="text-info socauchon">Số Câu Đã Chọn : <span id="socauchon">0</span></h6>


                                <table id="employeeTable" class="display questionTable" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th class="first-column"><input id="selectAllCheckbox" class="checkbox1" type="checkbox"></th>
                                            <th>Name</th>
                                            <th>Topic</th>

                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>

                                            <th></th>
                                            <th>Name</th>
                                            <th>Topic</th>

                                        </tr>
                                    </tfoot>
                                </table>

                            </section>
                            <hr />


                        </div>


                        @*</form>*@
                    }
                </div>
            </div>


        </div>
        <!-- /.card-body -->
        <!-- /.card-footer-->
    </div>

</div>
<!-- Bootstrap CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap4.min.css" rel="stylesheet">

@*<link href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.6/semantic.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.semanticui.min.css" rel="stylesheet" />*@
@section scripts{
    <!-- jQuery (cần cho Bootstrap và Datatables) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <!-- Bootstrap Datatables JS -->
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js"></script>

    @*<script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.semanticui.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.6/semantic.min.js"></script>*@
    <script>
        $(document).ready(function () {


            $("#employeeTable").DataTable({

                "ajax": {
                    "url": "/Admin/DeThi/GetList",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    {
                        "orderable": false,
                        "data": "IdQuestion",

                        "render": function (data, type, row) {
                            // Thêm một checkbox vào cột đầu tiên
                            return ' <div class="form-check"><input class="cbkItem" type="checkbox" value="' + data + '" id="flexCheckDefault"></div>';
                        },
                        "searchable": false, // Vô hiệu hóa chức năng tìm kiếm trên cột này
                        "autoFill": true
                    },

                    { "data": "Contentt" },
                    { "data": "TopicName" }

                ],

                "serverSide": "true",
                "order": [0, "asc"],
                "processing": "true",
                "language": {
                    "processing": "processing... please wait"
                },

            });
            // sự kiện load lại dữ liệu vẫn dùng
            $("#employeeTable").on("draw.dt", function () {
                // Xử lý sự kiện khi DataTables được vẽ lại sau tìm kiếm hoặc phân trang
                $(".cbkItem").change(function () {
                    var checkedCheckboxes = $(".cbkItem:checked");
                    var count = checkedCheckboxes.length;
                    updateSelectedCount();
                });
            });
            // click all checked
            $('#selectAllCheckbox').change(function () {
                // Lấy giá trị tích hay không tích của checkbox "selectAllCheckbox"
                var isChecked = $(this).prop('checked');

                // Tìm tất cả các checkbox với class "cbkItem" và thiết lập giá trị tích dựa vào giá trị của "selectAllCheckbox"
                $('.cbkItem').prop('checked', isChecked);
                updateSelectedCount();
            });

            // thay đổi số câu hỏi
            function updateSelectedCount() {
                var selectedCount = $('.cbkItem:checked').length;
                $('#socauchon').text(selectedCount);
                $('#socauhoi1').val(selectedCount);
            }
            // hàm lấy giá trị id câu hỏi đưa vào mảng
            function getCheckedValues() {
                var checkedValues = [];
                $('.cbkItem:checked').each(function () {
                    checkedValues.push($(this).val());
                });
                return checkedValues;
            }
            //thêm bài thi cùng câu hỏi bằng ajax




            $('#submitcl123').click(function () {
                var checkvalue = getCheckedValues();
                var queryString = checkvalue.map(questionId => "questionIds=" + questionId).join("&");
                var examData = $('#examForm').serialize(); // các trường thêm Exam
                //trường thêm câu hỏi bằng chọn
                $.ajax({
                    type: "POST",
                    url: "/Admin/DeThi/AddExamWithQuestions",
                    data: examData + "&" + queryString,
                    success: function (re) {
                        if (re.success) {
                            toastr.success('Thêm Thành Công', 'Title');
                        } else {
                            toastr.error('Thêm Thất bại ', 'Title');
                        }
                    },
                    error: function (error) {
                        toastr.error('Thêm Thất Bại', 'Title');
                        console.error(error);
                    }
                });
            });

        });




    </script>









}

DoAnCs/Areas/Admin/Views/DeThi/CauHoiKhongthuocBaiThi.cshtml
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" style="width:800px; padding:30px;">
            <div class="modal-header">
                <h2 class="modal-title  align-content-center" id="exampleModalLongTitle">Thêm câu hỏi vào đề thi</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table id="khongThuoc" style="width:100%" class="display questionTable">
                    <thead>
                        <tr>

                            <th>Name</th>
                            <th>Topic</th>
                            <th style="width:60px;"></th>
                        </tr>
                    </thead>
                  
                  
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div>

DoAnCs/Areas/Admin/Views/DeThi/Partial_CauHoi.cshtml
@model IEnumerable<DoAnCs.Models.Question>

<div class="modal-content">
    <div class="modal-header">
        <span class="close">&times;</span>

    </div>
    <div class="modal-body" id="Preview">
        @if (Model.Any() && Model != null)
        {
            var i = 1;
            <table>
                <thead>
                    <tr>
                        <th>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="SelecAll" value="">
                            </div>
                            STT
                        </th>
                        <th>TênCâuHỏi</th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {

                        <tr id="trow_@item.IdQuestion">
                            <td>
                                <div class="form-check">
                                    <input class="cbkItem" type="checkbox" value="@item.IdQuestion" id="flexCheckDefault">

                                </div>
                                <p>@i</p>
                            </td>

                            <td> @Html.Raw(HttpUtility.HtmlDecode(item.Contentt))</td>
                         
                        </tr>

                        i++;
                    }



                </tbody>
            </table>

        }
        else
        {
            <p>Không Có Gì</p>
        }
    </div>
    <div id="myPager" class="modal-footer">
        @if (ViewBag.TotalPages > 1)
        {
            <div class="btn-group">
                @for (int i = 1; i <= ViewBag.TotalPages; i++)
                {
                    <button type="button" class="btn btn-primary btn-page" data-page="@i">@i</button>
                }
            </div>
        }
        <button class="btn btn-primary" id="AddAllQuestion1"> Thêm </button>
    </div>
</div>